[package]
name = "razor-stable-swap"
version = "1.0.0"
authors = []

[addresses]
razor_stable_swap = "_"
admin = "0x0133e0a39bdfcf5bbde2b1f4def9f36b2842693345ccc49d6aa6f2ee8c7ccf9a"
fee_admin = "0x703c20063317af987ab7fc191103d7cd27369ee1322a90d23b174ee393ca9839"
razor_libs = "0xae5ff4c02c7ae43f57c8502c6623747d81bb7dbc6613152eca987a7e1f930727"

[dev-addresses]

[dependencies]
AptosFramework = {git = 'https://github.com/aptos-labs/aptos-core.git',rev='main',subdir = 'aptos-move/framework/aptos-framework'}
AptosStdlib = {git = 'https://github.com/aptos-labs/aptos-core.git',rev='main',subdir = 'aptos-move/framework/aptos-stdlib'}
RazorLibs = {git = 'https://github.com/razorlabsorg/razor-libs.git',rev='main'}

[dev-dependencies]
